### PR TITLE
Add support for different units in `TextStyle.lineHeight`

### PR DESCRIPTION
**Pull request by blinpete**
This pull request adds support for different line height units.

### Issue

Currently [`TextStyle.lineHeight`](https://github.com/marcomontalbano/figma-export/blob/a729f1b9b4be40caaff945d9a3811209eef5178b/packages/types/src/styles/TextStyle.ts#L16) is a unitless number and stores `lineHeightPx` coming from [figma-js](https://jemgold.github.io/figma-js/interfaces/typestyle.html#lineheightpx) and [Figma API](https://www.figma.com/developers/api#files-types) itself. Which results in unexpected behavior when you set up your line height in font size percentage but still end up with pixels exported.

Having this as the default behavior is a bit confusing cuz [a unitless line height in web](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#values) development carries a different meaning.

### Solution

Figma supports 3 line height units `PIXELS`, `INTRINSIC_%` and `FONT_SIZE_%`.
Now `TextStyle.lineHeight` is a string and the `textStyle` parser handles all of the units correctly according to `lineHeightUnit` value.

### The difference in behavior

```ts
{
  type: "TEXT",
  style: {
      ...,
      lineHeightPx: 30,
      lineHeightPercent: 106,
      lineHeightPercentFontSize: 125,
      lineHeightUnit: ... // "PIXELS" or "INTRINSIC_%" or "FONT_SIZE_%"
  }
}
```

Considering this Figma `TextNode` here's how `figma-export` handles a line height depending on the `lineHeightUnit` key:

| Figma API `lineHeightUnit` | figma-export (main branch) | figma-export (on this branch) |
|----------------------------|----------------------------|-------------------------------|
|                     PIXELS |         `lineHeight: 30` ✅ |       `lineHeight: "30px"` ✅ |
|                INTRINSIC_% |         `lineHeight: 30` ❌ |       `lineHeight: "106%"` ✅ |
|                FONT_SIZE_% |         `lineHeight: 30` ❌ |       `lineHeight: "1.25"` ✅ |

---

@marcomontalbano Thanks for your work, `figma-export` is damn well designed!

### CODE REVIEW

**Comment by marcomontalbano** [comment]
Hi @blinpete, thanks a lot for your PR, it looks amazing!

I have just one doubt. In my figma-export [example file](https://www.figma.com/file/fzYhvQpqwhZDUImRz431Qo/figma-export), I have two different texts (different font-size) with line-height set to `Auto`.

```jsonc
// first text with line-height: Auto
{
  type: "TEXT",
  style: {
    ...,
    "fontSize": 14,
    "lineHeightPx": 16.40625,
    "lineHeightPercent": 100,
    "lineHeightUnit": "INTRINSIC_%"
  }
}

// second text with line-height: Auto
{
  type: "TEXT",
  style: {
    ...,
    "fontSize": 18,
    "lineHeightPx": 21.09375,
    "lineHeightPercent": 100,
    "lineHeightUnit": "INTRINSIC_%"
  }
}
```

Before this change, the line height was generated as `16.40625px` and `21.09375px` respectively. With this PR it will change to `100%` for both and it will render differently from before (I tested [here](https://figma-export.marcomontalbano.com/#figma-styles) for the final result and it looks like a breaking change).

What do you think about it? How can we manage it?

**Comment by blinpete** [comment]
Hey @marcomontalbano!

not sure about this

1. we can try to dive into typography and calculate what Figma is doing under the hood. There are tricks like [basekick](https://css-tricks.com/how-to-tame-line-height-in-css/) and [capsizecss](https://www.npmjs.com/package/@capsizecss/core). seems like SEEK-OSS are far ahead here.
2. or we can revert `INTRINSIC_%` if-branch to use pixels. [`INTRINSIC_%` is deprecated](https://www.figma.com/developers/api#files-types) by Figma anyway

what are your thoughts on this?

**Comment by marcomontalbano** [comment]
I would proceed with the option 2. Since `INTRINSIC_%` is deprecated, this way we'll not have to change the code in future Figma API releases.

**Comment by blinpete** [comment]
@marcomontalbano 
Yeah sure, just pushed the commit doing the 2nd option 👍

**Review by marcomontalbano — APPROVED** [review]
Well done, thanks!

**Comment by marcomontalbano** [comment]
I just released [v4.8.0-alpha.1](https://github.com/marcomontalbano/figma-export/releases/tag/v4.8.0-alpha.1)

Let me know if everything is working as expected.

**Pull request merged**
